version: '2'

services:
  hearts:
    image: hearts
    hostname: hearts
    entrypoint:
    - sh
    - -c
    - "/setup/run.sh;sleep infinity"
    volumes:
      - ./:/hearts
    privileged: true
    restart: always
    ports:
    - 6080:6080
    - 8888:8888
